// Paquet de départ — vocabulaire arabe (toujours vocalisé, avec les voyelles).
// Chaque mot = { ar, translit, fr, cat }  (cat = catégorie / thème).
// Tu peux éditer cette liste à la main, ou ajouter des mots directement dans le site.
// Bouton « Réinitialiser » = repartir de cette liste.

window.DEFAULT_WORDS = [
  // 🛏️ La chambre et la maison
  { ar: "فِي غُرْفَتِي", translit: "fī ghurfatī", fr: "dans ma chambre", cat: "Chambre & maison" },
  { ar: "سَرِيرٌ", translit: "sarīrun", fr: "un lit", cat: "Chambre & maison" },
  { ar: "بِطَّانِيَّةٌ", translit: "biṭṭāniyyatun", fr: "une couverture", cat: "Chambre & maison" },
  { ar: "خِزَانَةٌ", translit: "khizānatun", fr: "une armoire / un placard", cat: "Chambre & maison" },
  { ar: "أَنَامُ عَلَى السَّرِيرِ", translit: "anāmu ʿalā s-sarīri", fr: "je dors sur le lit", cat: "Chambre & maison" },
  { ar: "أَضَعُ", translit: "aḍaʿu", fr: "je mets / je pose", cat: "Chambre & maison" },
  { ar: "أُغَطِّي", translit: "ughaṭṭī", fr: "je couvre", cat: "Chambre & maison" },
  { ar: "الوِسَادَةُ", translit: "al-wisādatu", fr: "l'oreiller", cat: "Chambre & maison" },
  { ar: "المَكْتَبُ", translit: "al-maktabu", fr: "le bureau de travail", cat: "Chambre & maison" },
  { ar: "أَقْلَامٌ", translit: "aqlāmun", fr: "des stylos", cat: "Chambre & maison" },
  { ar: "حَاسُوبٌ", translit: "ḥāsūbun", fr: "ordinateur", cat: "Chambre & maison" },
  { ar: "المِصْبَاحُ", translit: "al-miṣbāḥu", fr: "la lampe", cat: "Chambre & maison" },
  { ar: "نَافِذَةٌ", translit: "nāfidhatun", fr: "fenêtre", cat: "Chambre & maison" },
  { ar: "نَوَافِذُ", translit: "nawāfidhu", fr: "fenêtres (pluriel)", cat: "Chambre & maison" },
  { ar: "سِتَارَةٌ", translit: "sitāratun", fr: "rideau", cat: "Chambre & maison" },
  { ar: "سَتَائِرُ", translit: "satāʾiru", fr: "rideaux", cat: "Chambre & maison" },
  { ar: "سَجَّادَةٌ", translit: "sajjādatun", fr: "tapis", cat: "Chambre & maison" },
  { ar: "جُرَابٌ", translit: "jurābun", fr: "chaussette", cat: "Chambre & maison" },
  { ar: "جَوَارِبُ", translit: "jawāribu", fr: "chaussettes", cat: "Chambre & maison" },

  // 🧼 La salle de bain et l'hygiène
  { ar: "فِي الحَمَّامِ", translit: "fī l-ḥammāmi", fr: "dans la salle de bain", cat: "Salle de bain" },
  { ar: "حَوْضٌ", translit: "ḥawḍun", fr: "un lavabo / une baignoire", cat: "Salle de bain" },
  { ar: "المُغْتَسَلُ", translit: "al-mughtasalu", fr: "le lavabo", cat: "Salle de bain" },
  { ar: "صَابُونٌ", translit: "ṣābūnun", fr: "savon", cat: "Salle de bain" },
  { ar: "مِرْآةٌ", translit: "mirʾātun", fr: "miroir", cat: "Salle de bain" },
  { ar: "مِنْشَفَةٌ", translit: "minshafatun", fr: "serviette / essuie-tout", cat: "Salle de bain" },
  { ar: "جَسَدٌ", translit: "jasadun", fr: "corps", cat: "Salle de bain" },
  { ar: "جِسْمٌ", translit: "jismun", fr: "corps", cat: "Salle de bain" },
  { ar: "أُنَظِّفُ", translit: "unaẓẓifu", fr: "je nettoie", cat: "Salle de bain" },
  { ar: "سَلَّةُ الغَسِيلِ", translit: "sallatu l-ghasīli", fr: "panier à linge", cat: "Salle de bain" },
  { ar: "أَجْلِسُ", translit: "ajlisu", fr: "je m'assois", cat: "Salle de bain" },
  { ar: "أَبُولُ", translit: "abūlu", fr: "je fais pipi", cat: "Salle de bain" },
  { ar: "أَقْضِي حَاجَتِي", translit: "aqḍī ḥājatī", fr: "faire ses besoins", cat: "Salle de bain" },
  { ar: "البُرَازُ", translit: "al-burāzu", fr: "les selles / matières fécales", cat: "Salle de bain" },

  // 🍳 La cuisine, les ustensiles et les verbes
  { ar: "المَطْبَخُ", translit: "al-maṭbakhu", fr: "la cuisine", cat: "Cuisine" },
  { ar: "الأَوَانِي", translit: "al-awānī", fr: "la vaisselle", cat: "Cuisine" },
  { ar: "نُجَفِّفُ", translit: "nujaffifu", fr: "nous séchons", cat: "Cuisine" },
  { ar: "تَسْتَعْجِلُ", translit: "tastaʿjilu", fr: "tu te dépêches / tu es pressé", cat: "Cuisine" },
  { ar: "أَسْتَعْمِلُ", translit: "astaʿmilu", fr: "j'utilise", cat: "Cuisine" },
  { ar: "الفُرْنُ", translit: "al-furnu", fr: "le four", cat: "Cuisine" },
  { ar: "المَوْقِدُ", translit: "al-mawqidu", fr: "la plaque de cuisson / le réchaud", cat: "Cuisine" },
  { ar: "شَفَّاطٌ", translit: "shaffāṭun", fr: "hotte aspirante", cat: "Cuisine" },
  { ar: "المِصْفَاةُ", translit: "al-miṣfātu", fr: "la passoire", cat: "Cuisine" },
  { ar: "أُصَفِّي الطَّعَامَ فِي المَاءِ", translit: "uṣaffī ṭ-ṭaʿāma fī l-māʾi", fr: "j'égoutte la nourriture (dans l'eau)", cat: "Cuisine" },
  { ar: "خَلَّاطٌ", translit: "khallāṭun", fr: "mixeur", cat: "Cuisine" },
  { ar: "إِبْرِيقُ الشَّايِ", translit: "ibrīqu sh-shāyi", fr: "la théière", cat: "Cuisine" },
  { ar: "الشَّوْكَةُ", translit: "ash-shawkatu", fr: "la fourchette", cat: "Cuisine" },
  { ar: "المِقْلَاةُ", translit: "al-miqlātu", fr: "la poêle", cat: "Cuisine" },
  { ar: "القِدْرُ", translit: "al-qidru", fr: "la marmite / la casserole", cat: "Cuisine" },
  { ar: "لَوْحَةُ التَّقْطِيعِ", translit: "lawḥatu t-taqṭīʿi", fr: "planche à découper", cat: "Cuisine" },
  { ar: "أَطْبُخُ الطَّعَامَ", translit: "aṭbukhu ṭ-ṭaʿāma", fr: "je cuisine / je prépare le repas", cat: "Cuisine" },
  { ar: "أَكْوَابٌ", translit: "akwābun", fr: "des verres", cat: "Cuisine" },
  { ar: "صَحْنٌ", translit: "ṣaḥnun", fr: "assiette", cat: "Cuisine" },
  { ar: "صُحُونٌ", translit: "ṣuḥūnun", fr: "assiettes", cat: "Cuisine" },
  { ar: "المِلْعَقَةُ", translit: "al-milʿaqatu", fr: "la cuillère", cat: "Cuisine" },
  { ar: "الغَلَّايَةُ", translit: "al-ghallāyatu", fr: "la bouilloire", cat: "Cuisine" },
  { ar: "السِّكِّينُ", translit: "as-sikkīnu", fr: "le couteau", cat: "Cuisine" },
  { ar: "مِكْوَاةٌ", translit: "mikwātun", fr: "un fer à repasser", cat: "Cuisine" },
  { ar: "أَكْوِي", translit: "akwī", fr: "je repasse", cat: "Cuisine" },
  { ar: "إِبْرِيقٌ", translit: "ibrīqun", fr: "carafe / broc", cat: "Cuisine" },
  { ar: "أُفْرِغُ", translit: "ufrighu", fr: "je verse / je vide", cat: "Cuisine" },
  { ar: "أَفْرَغَ", translit: "afragha", fr: "renverser / vider (la nourriture)", cat: "Cuisine" },
  { ar: "الحِسَاءُ", translit: "al-ḥisāʾu", fr: "la soupe", cat: "Cuisine" },
  { ar: "بَيْضٌ", translit: "bayḍun", fr: "des œufs", cat: "Cuisine" }
];

// =====================================================================
// Paquets de départ par DIALECTE (vrai parler, pas l'arabe standard).
// Clés = id du preset (voir LANG_PRESETS dans app.js).
// Chaque mot = { ar, translit, fr, cat }. Termes vocalisés.
// =====================================================================
window.DIALECT_PACKS = {

  // 🇲🇦 Darija marocain
  darija: [
    { ar: "بْغِيت", translit: "bghit", fr: "je veux", cat: "Mots du quotidien" },
    { ar: "وَاخّا", translit: "wakha", fr: "d'accord / OK", cat: "Mots du quotidien" },
    { ar: "بِزّاف", translit: "bezzaf", fr: "beaucoup / trop", cat: "Mots du quotidien" },
    { ar: "شْوِيَّة", translit: "chwiya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "دَابَا", translit: "daba", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "مَزْيَان", translit: "mzyan", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "صَافِي", translit: "safi", fr: "ça suffit / voilà", cat: "Mots du quotidien" },
    { ar: "خُويَا", translit: "khoya", fr: "mon frère / mon pote", cat: "Mots du quotidien" },
    { ar: "دْيَالِي", translit: "dyali", fr: "à moi / le mien", cat: "Mots du quotidien" },
    { ar: "الحَانُوت", translit: "l-ḥanut", fr: "l'épicerie du coin", cat: "Mots du quotidien" },
    { ar: "أَتَاي", translit: "atay", fr: "le thé (à la menthe)", cat: "Mots du quotidien" },
    { ar: "كِي دَايِر؟", translit: "ki dayer?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "شْحَال؟", translit: "chḥal?", fr: "combien ?", cat: "Questions & politesse" },
    { ar: "فِين؟", translit: "fin?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيفَاش؟", translit: "kifach?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عْلاش؟", translit: "3lach?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عَافَاك", translit: "3afak", fr: "s'il te plaît", cat: "Questions & politesse" },
    { ar: "مَاكَايْن مُشْكِيل", translit: "makayn mushkil", fr: "il n'y a pas de problème", cat: "Questions & politesse" },
    { ar: "بَرَاكَا", translit: "baraka", fr: "ça suffit / arrête", cat: "Questions & politesse" },
  ],

  // 🇪🇬 Égyptien
  egy: [
    { ar: "عَايِز", translit: "3ayez", fr: "je veux (homme)", cat: "Mots du quotidien" },
    { ar: "عَايْزَة", translit: "3ayza", fr: "je veux (femme)", cat: "Mots du quotidien" },
    { ar: "دِلْوَقْتِي", translit: "delwa2ti", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "كِدَه", translit: "keda", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "قَوِي", translit: "2awi", fr: "très / beaucoup", cat: "Mots du quotidien" },
    { ar: "شْوَيَّة", translit: "shwaya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "كْوَيِّس", translit: "kwayyes", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "حَاجَة", translit: "ḥaga", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "خَلَاص", translit: "khalaṣ", fr: "fini / ça suffit", cat: "Mots du quotidien" },
    { ar: "النَّهَارْدَه", translit: "el-naharda", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "بُكْرَة", translit: "bokra", fr: "demain", cat: "Mots du quotidien" },
    { ar: "إِمْبَارِح", translit: "embareḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "إِزَّيَّك؟", translit: "ezzayyak?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "فِين؟", translit: "fein?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "إِزَّاي؟", translit: "ezzay?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عَايِز إِيه؟", translit: "3ayez eh?", fr: "tu veux quoi ?", cat: "Questions & politesse" },
    { ar: "لِيه؟", translit: "leh?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عَشَان", translit: "3ashan", fr: "parce que / pour", cat: "Questions & politesse" },
    { ar: "مَعْلِشّ", translit: "ma3lesh", fr: "c'est pas grave / désolé", cat: "Questions & politesse" },
  ],

  // 🇱🇧 Libanais
  leb: [
    { ar: "بَدِّي", translit: "baddi", fr: "je veux", cat: "Mots du quotidien" },
    { ar: "هَلَّق", translit: "halla2", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "هِيك", translit: "heik", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "كْتِير", translit: "ktir", fr: "beaucoup / très", cat: "Mots du quotidien" },
    { ar: "شْوَيّ", translit: "shwayy", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "مْنِيح", translit: "mnih", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "شِي", translit: "shi", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "خَلَص", translit: "khalaṣ", fr: "fini / ça suffit", cat: "Mots du quotidien" },
    { ar: "يَعْنِي", translit: "ya3ni", fr: "c'est-à-dire / genre", cat: "Mots du quotidien" },
    { ar: "اليَوْم", translit: "lyom", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "بُكْرَا", translit: "bukra", fr: "demain", cat: "Mots du quotidien" },
    { ar: "مْبَارِح", translit: "mbeireḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "كِيفَك؟", translit: "kifak?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "شُو؟", translit: "shu?", fr: "quoi ?", cat: "Questions & politesse" },
    { ar: "وِين؟", translit: "wein?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيف؟", translit: "kif?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "لِيش؟", translit: "leish?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "لَأَنُّو", translit: "la2anno", fr: "parce que", cat: "Questions & politesse" },
    { ar: "مَعْلِيش", translit: "ma3lish", fr: "c'est pas grave", cat: "Questions & politesse" },
  ],

  // 🇹🇳 Tunisien
  tun: [
    { ar: "نْحِبّ", translit: "nḥeb", fr: "je veux / j'aime", cat: "Mots du quotidien" },
    { ar: "تَوَّا", translit: "tawwa", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "هَكَّا", translit: "hakka", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "بَرْشَا", translit: "barcha", fr: "beaucoup / très", cat: "Mots du quotidien" },
    { ar: "شْوَيَّة", translit: "chwaya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "بَاهِي", translit: "behi", fr: "bien / bon / OK", cat: "Mots du quotidien" },
    { ar: "حَاجَة", translit: "ḥaja", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "بَرْكَة", translit: "barka", fr: "ça suffit / arrête", cat: "Mots du quotidien" },
    { ar: "فَمَّا", translit: "famma", fr: "il y a", cat: "Mots du quotidien" },
    { ar: "اليُوم", translit: "lyoum", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "غُدْوَة", translit: "ghodwa", fr: "demain", cat: "Mots du quotidien" },
    { ar: "البَارِح", translit: "el-bareḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "شْنُوَّة؟", translit: "chnowa?", fr: "quoi ?", cat: "Questions & politesse" },
    { ar: "شْنِيَّة أَحْوَالِك؟", translit: "chnia aḥwalek?", fr: "comment vas-tu ?", cat: "Questions & politesse" },
    { ar: "وِين؟", translit: "win?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيفَاش؟", translit: "kifech?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عْلَاش؟", translit: "3lech?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عْلَى خَاطِر", translit: "3la khater", fr: "parce que", cat: "Questions & politesse" },
    { ar: "يِزِّي", translit: "yezzi", fr: "arrête / ça suffit", cat: "Questions & politesse" },
  ],

};
