// Paquet de départ — vocabulaire arabe (toujours vocalisé, avec les voyelles).
// Chaque mot = { ar, translit, fr, cat }  (cat = catégorie / thème).
// Tu peux éditer cette liste à la main, ou ajouter des mots directement dans le site.
// Bouton « Réinitialiser » = repartir de cette liste.

window.DEFAULT_WORDS = [
  // 🛏️ La chambre et la maison
  { ar: "فِي غُرْفَتِي", translit: "fī ghurfatī", fr: "dans ma chambre", cat: "Chambre & maison" },
  { ar: "سَرِيرٌ", translit: "sarīrun", fr: "un lit", cat: "Chambre & maison" },
  { ar: "بِطَّانِيَّةٌ", translit: "biṭṭāniyyatun", fr: "une couverture", cat: "Chambre & maison" },
  { ar: "خِزَانَةٌ", translit: "khizānatun", fr: "une armoire / un placard", cat: "Chambre & maison" },
  { ar: "أَنَامُ عَلَى السَّرِيرِ", translit: "anāmu ʿalā s-sarīri", fr: "je dors sur le lit", cat: "Chambre & maison" },
  { ar: "أَضَعُ", translit: "aḍaʿu", fr: "je mets / je pose", cat: "Chambre & maison" },
  { ar: "أُغَطِّي", translit: "ughaṭṭī", fr: "je couvre", cat: "Chambre & maison" },
  { ar: "الوِسَادَةُ", translit: "al-wisādatu", fr: "l'oreiller", cat: "Chambre & maison" },
  { ar: "المَكْتَبُ", translit: "al-maktabu", fr: "le bureau de travail", cat: "Chambre & maison" },
  { ar: "أَقْلَامٌ", translit: "aqlāmun", fr: "des stylos", cat: "Chambre & maison" },
  { ar: "حَاسُوبٌ", translit: "ḥāsūbun", fr: "ordinateur", cat: "Chambre & maison" },
  { ar: "المِصْبَاحُ", translit: "al-miṣbāḥu", fr: "la lampe", cat: "Chambre & maison" },
  { ar: "نَافِذَةٌ", translit: "nāfidhatun", fr: "fenêtre", cat: "Chambre & maison" },
  { ar: "نَوَافِذُ", translit: "nawāfidhu", fr: "fenêtres (pluriel)", cat: "Chambre & maison" },
  { ar: "سِتَارَةٌ", translit: "sitāratun", fr: "rideau", cat: "Chambre & maison" },
  { ar: "سَتَائِرُ", translit: "satāʾiru", fr: "rideaux", cat: "Chambre & maison" },
  { ar: "سَجَّادَةٌ", translit: "sajjādatun", fr: "tapis", cat: "Chambre & maison" },
  { ar: "جُرَابٌ", translit: "jurābun", fr: "chaussette", cat: "Chambre & maison" },
  { ar: "جَوَارِبُ", translit: "jawāribu", fr: "chaussettes", cat: "Chambre & maison" },

  // 🧼 La salle de bain et l'hygiène
  { ar: "فِي الحَمَّامِ", translit: "fī l-ḥammāmi", fr: "dans la salle de bain", cat: "Salle de bain" },
  { ar: "حَوْضٌ", translit: "ḥawḍun", fr: "un lavabo / une baignoire", cat: "Salle de bain" },
  { ar: "المُغْتَسَلُ", translit: "al-mughtasalu", fr: "le lavabo", cat: "Salle de bain" },
  { ar: "صَابُونٌ", translit: "ṣābūnun", fr: "savon", cat: "Salle de bain" },
  { ar: "مِرْآةٌ", translit: "mirʾātun", fr: "miroir", cat: "Salle de bain" },
  { ar: "مِنْشَفَةٌ", translit: "minshafatun", fr: "serviette / essuie-tout", cat: "Salle de bain" },
  { ar: "جَسَدٌ", translit: "jasadun", fr: "corps", cat: "Salle de bain" },
  { ar: "جِسْمٌ", translit: "jismun", fr: "corps", cat: "Salle de bain" },
  { ar: "أُنَظِّفُ", translit: "unaẓẓifu", fr: "je nettoie", cat: "Salle de bain" },
  { ar: "سَلَّةُ الغَسِيلِ", translit: "sallatu l-ghasīli", fr: "panier à linge", cat: "Salle de bain" },
  { ar: "أَجْلِسُ", translit: "ajlisu", fr: "je m'assois", cat: "Salle de bain" },
  { ar: "أَبُولُ", translit: "abūlu", fr: "je fais pipi", cat: "Salle de bain" },
  { ar: "أَقْضِي حَاجَتِي", translit: "aqḍī ḥājatī", fr: "faire ses besoins", cat: "Salle de bain" },
  { ar: "البُرَازُ", translit: "al-burāzu", fr: "les selles / matières fécales", cat: "Salle de bain" },

  // 🍳 La cuisine, les ustensiles et les verbes
  { ar: "المَطْبَخُ", translit: "al-maṭbakhu", fr: "la cuisine", cat: "Cuisine" },
  { ar: "الأَوَانِي", translit: "al-awānī", fr: "la vaisselle", cat: "Cuisine" },
  { ar: "نُجَفِّفُ", translit: "nujaffifu", fr: "nous séchons", cat: "Cuisine" },
  { ar: "تَسْتَعْجِلُ", translit: "tastaʿjilu", fr: "tu te dépêches / tu es pressé", cat: "Cuisine" },
  { ar: "أَسْتَعْمِلُ", translit: "astaʿmilu", fr: "j'utilise", cat: "Cuisine" },
  { ar: "الفُرْنُ", translit: "al-furnu", fr: "le four", cat: "Cuisine" },
  { ar: "المَوْقِدُ", translit: "al-mawqidu", fr: "la plaque de cuisson / le réchaud", cat: "Cuisine" },
  { ar: "شَفَّاطٌ", translit: "shaffāṭun", fr: "hotte aspirante", cat: "Cuisine" },
  { ar: "المِصْفَاةُ", translit: "al-miṣfātu", fr: "la passoire", cat: "Cuisine" },
  { ar: "أُصَفِّي الطَّعَامَ فِي المَاءِ", translit: "uṣaffī ṭ-ṭaʿāma fī l-māʾi", fr: "j'égoutte la nourriture (dans l'eau)", cat: "Cuisine" },
  { ar: "خَلَّاطٌ", translit: "khallāṭun", fr: "mixeur", cat: "Cuisine" },
  { ar: "إِبْرِيقُ الشَّايِ", translit: "ibrīqu sh-shāyi", fr: "la théière", cat: "Cuisine" },
  { ar: "الشَّوْكَةُ", translit: "ash-shawkatu", fr: "la fourchette", cat: "Cuisine" },
  { ar: "المِقْلَاةُ", translit: "al-miqlātu", fr: "la poêle", cat: "Cuisine" },
  { ar: "القِدْرُ", translit: "al-qidru", fr: "la marmite / la casserole", cat: "Cuisine" },
  { ar: "لَوْحَةُ التَّقْطِيعِ", translit: "lawḥatu t-taqṭīʿi", fr: "planche à découper", cat: "Cuisine" },
  { ar: "أَطْبُخُ الطَّعَامَ", translit: "aṭbukhu ṭ-ṭaʿāma", fr: "je cuisine / je prépare le repas", cat: "Cuisine" },
  { ar: "أَكْوَابٌ", translit: "akwābun", fr: "des verres", cat: "Cuisine" },
  { ar: "صَحْنٌ", translit: "ṣaḥnun", fr: "assiette", cat: "Cuisine" },
  { ar: "صُحُونٌ", translit: "ṣuḥūnun", fr: "assiettes", cat: "Cuisine" },
  { ar: "المِلْعَقَةُ", translit: "al-milʿaqatu", fr: "la cuillère", cat: "Cuisine" },
  { ar: "الغَلَّايَةُ", translit: "al-ghallāyatu", fr: "la bouilloire", cat: "Cuisine" },
  { ar: "السِّكِّينُ", translit: "as-sikkīnu", fr: "le couteau", cat: "Cuisine" },
  { ar: "مِكْوَاةٌ", translit: "mikwātun", fr: "un fer à repasser", cat: "Cuisine" },
  { ar: "أَكْوِي", translit: "akwī", fr: "je repasse", cat: "Cuisine" },
  { ar: "إِبْرِيقٌ", translit: "ibrīqun", fr: "carafe / broc", cat: "Cuisine" },
  { ar: "أُفْرِغُ", translit: "ufrighu", fr: "je verse / je vide", cat: "Cuisine" },
  { ar: "أَفْرَغَ", translit: "afragha", fr: "renverser / vider (la nourriture)", cat: "Cuisine" },
  { ar: "الحِسَاءُ", translit: "al-ḥisāʾu", fr: "la soupe", cat: "Cuisine" },
  { ar: "بَيْضٌ", translit: "bayḍun", fr: "des œufs", cat: "Cuisine" },

  // 🧭 Kit de survie (arabe littéraire)
  { ar: "السَّلَامُ عَلَيْكُمْ", translit: "as-salāmu ʿalaykum", fr: "bonjour (salut)", cat: "Kit de survie" },
  { ar: "شُكْرًا", translit: "shukran", fr: "merci", cat: "Kit de survie" },
  { ar: "نَعَمْ", translit: "naʿam", fr: "oui", cat: "Kit de survie" },
  { ar: "لَا", translit: "lā", fr: "non", cat: "Kit de survie" },
  { ar: "بِكَمْ هَذَا؟", translit: "bikam hādhā?", fr: "combien ça coûte ?", cat: "Kit de survie" },
  { ar: "أَيْنَ...؟", translit: "ayna...?", fr: "où est... ?", cat: "Kit de survie" },
  { ar: "لَا أَفْهَمُ", translit: "lā afhamu", fr: "je ne comprends pas", cat: "Kit de survie" },
  { ar: "أَيْنَ الحَمَّامُ؟", translit: "ayna l-ḥammāmu?", fr: "où sont les toilettes ?", cat: "Kit de survie" },
  { ar: "هَلْ يُمْكِنُكَ مُسَاعَدَتِي؟", translit: "hal yumkinuka musāʿadatī?", fr: "peux-tu m'aider ?", cat: "Kit de survie" },
  { ar: "الحِسَابُ مِنْ فَضْلِكَ", translit: "al-ḥisābu min faḍlika", fr: "l'addition s'il vous plaît", cat: "Kit de survie" },
  { ar: "مَعَ السَّلَامَةِ", translit: "maʿa s-salāmati", fr: "au revoir", cat: "Kit de survie" },

  // 🙋 Se présenter (arabe littéraire)
  { ar: "اِسْمِي...", translit: "ismī...", fr: "je m'appelle...", cat: "Se présenter" },
  { ar: "عُمْرِي ... سَنَةً", translit: "ʿumrī ... sanatan", fr: "j'ai ... ans", cat: "Se présenter" },
  { ar: "أَنَا فَرَنْسِيٌّ", translit: "anā faransiyyun", fr: "je suis français", cat: "Se présenter" },
  { ar: "أَسْكُنُ فِي...", translit: "askunu fī...", fr: "j'habite à...", cat: "Se présenter" },
  { ar: "تَشَرَّفْنَا", translit: "tasharrafnā", fr: "enchanté", cat: "Se présenter" },
  { ar: "أَتَكَلَّمُ العَرَبِيَّةَ قَلِيلًا", translit: "atakallamu l-ʿarabiyyata qalīlan", fr: "je parle un peu arabe", cat: "Se présenter" },
  { ar: "مَا اسْمُكَ؟", translit: "mā ismuka?", fr: "comment t'appelles-tu ?", cat: "Se présenter" },

  // 🏡 Cours 2 — Ma maison & le jardin
  { ar: "بَيْتِي", translit: "baytī", fr: "ma maison", cat: "Cours 2" },
  { ar: "الْحَدِيقَةُ", translit: "al-ḥadīqatu", fr: "le jardin", cat: "Cours 2" },
  { ar: "جَمِيلَةٌ", translit: "jamīlatun", fr: "beau / belle", cat: "Cours 2" },
  { ar: "خَضْرَاءُ", translit: "khaḍrāʾu", fr: "vert / verte", cat: "Cours 2" },
  { ar: "وَاسِعَةٌ جِدًّا", translit: "wāsiʿatun jiddan", fr: "très spacieuse / grande", cat: "Cours 2" },
  { ar: "أَشْجَارٌ عَالِيَةٌ", translit: "ashjārun ʿāliyatun", fr: "des arbres hauts", cat: "Cours 2" },
  { ar: "أَزْهَارٌ مُلَوَّنَةٌ", translit: "azhārun mulawwanatun", fr: "des fleurs colorées", cat: "Cours 2" },
  { ar: "شَمَّ / يَشُمُّ / الشَّمّ", translit: "shamma / yashummu / ash-shamm", fr: "sentir / il sent / l'odorat", cat: "Cours 2" },
  { ar: "الرَّائِحَةُ", translit: "ar-rāʾiḥatu", fr: "l'odeur", cat: "Cours 2" },
  { ar: "الْوُرُودُ الزَّكِيَّةُ", translit: "al-wurūdu z-zakiyyatu", fr: "les roses parfumées", cat: "Cours 2" },
  { ar: "الْجَانِبِ الْأَيْسَرِ", translit: "al-jānibi l-aysari", fr: "le côté gauche", cat: "Cours 2" },
  { ar: "أُرْجُوحَةٌ صَغِيرَةٌ", translit: "urjūḥatun ṣaghīratun", fr: "une petite balançoire", cat: "Cours 2" },
  { ar: "أَلْعَبُ مَعَ أَخِي", translit: "alʿabu maʿa akhī", fr: "je joue avec mon frère", cat: "Cours 2" },
  { ar: "فِي الْمَسَاءِ", translit: "fī l-masāʾi", fr: "le soir", cat: "Cours 2" },
  { ar: "فِي الْوَسَطِ", translit: "fī l-wasaṭi", fr: "au milieu", cat: "Cours 2" },
  { ar: "عُشْبٌ طَبِيعِيٌّ نَاعِمٌ ≠ عُشْبٌ صِنَاعِيٌّ", translit: "ʿushbun ṭabīʿiyyun nāʿimun ≠ ʿushbun ṣināʿiyyun", fr: "herbe naturelle douce ≠ herbe artificielle", cat: "Cours 2" },
  { ar: "أَجْلِسُ عَلَى", translit: "ajlisu ʿalā", fr: "je m'assieds sur", cat: "Cours 2" },
  { ar: "أَقْرَأُ كِتَاباً مُفِيداً", translit: "aqraʾu kitāban mufīdan", fr: "je lis un livre utile", cat: "Cours 2" },
  { ar: "تَطِيرُ فَرَاشَاتٌ", translit: "taṭīru farāshātun", fr: "des papillons volent", cat: "Cours 2" },
  { ar: "فَوْقَ النَّبَاتَاتِ", translit: "fawqa n-nabātāti", fr: "au-dessus des plantes", cat: "Cours 2" },
  { ar: "تُغَرِّدُ عَصَافِيرُ صَغِيرَةٌ", translit: "tugharridu ʿaṣāfīru ṣaghīratun", fr: "de petits oiseaux gazouillent", cat: "Cours 2" },
  { ar: "فَوْقَ الْأَغْصَانِ", translit: "fawqa l-aghṣāni", fr: "au-dessus des branches", cat: "Cours 2" },
  { ar: "طَاوِلَةٌ بَيْضَاءُ", translit: "ṭāwilatun bayḍāʾu", fr: "une table blanche", cat: "Cours 2" },
  { ar: "أَرْبَعَةُ كَرَاسِيَّ", translit: "arbaʿatu karāsiyya", fr: "quatre chaises", cat: "Cours 2" },
  { ar: "أَشْرَبُ الشَّايَ", translit: "ashrabu sh-shāya", fr: "je bois du thé", cat: "Cours 2" },
  { ar: "مَعَ أُسْرَتِي", translit: "maʿa usratī", fr: "avec ma famille", cat: "Cours 2" },
  { ar: "أُحِبُّ", translit: "uḥibbu", fr: "j'aime", cat: "Cours 2" },
  { ar: "الْهَوَاءُ النَّقِيُّ", translit: "al-hawāʾu n-naqiyyu", fr: "l'air pur", cat: "Cours 2" },
  { ar: "عَصِيرٌ", translit: "ʿaṣīrun", fr: "jus", cat: "Cours 2" },
  { ar: "مُنْعِشٌ", translit: "munʿishun", fr: "rafraîchissant", cat: "Cours 2" },
  { ar: "الطَّبِيعَةُ", translit: "aṭ-ṭabīʿatu", fr: "la nature", cat: "Cours 2" },
  { ar: "إِشْعَالُ الضَّوْءِ", translit: "ishʿālu ḍ-ḍawʾi", fr: "allumer la lumière", cat: "Cours 2" },
  { ar: "أَطْفَأَ / يُطْفِئُ الضَّوْءَ", translit: "aṭfaʾa / yuṭfiʾu ḍ-ḍawʾa", fr: "éteindre / il éteint la lumière", cat: "Cours 2" },
  { ar: "يَذْهَبُ إِلَى غُرْفَةِ الِاسْتِحْمَامِ", translit: "yadhhabu ilā ghurfati l-istiḥmāmi", fr: "il va à la salle de bain", cat: "Cours 2" },
  { ar: "يَدْخُلُ فِي", translit: "yadkhulu fī", fr: "il entre dans", cat: "Cours 2" },
  { ar: "يَلْبَسُ مَلَابِسَهُ", translit: "yalbasu malābisahu", fr: "il met ses vêtements", cat: "Cours 2" },
  { ar: "أَزَالَ / يُزِيلُ الْمَلَابِسَ", translit: "azāla / yuzīlu l-malābisa", fr: "enlever / il enlève les vêtements", cat: "Cours 2" },
  { ar: "الْخِزَانَةُ", translit: "al-khizānatu", fr: "l'armoire", cat: "Cours 2" },
  { ar: "بِيجَامَا", translit: "bījāmā", fr: "pyjama", cat: "Cours 2" },
  { ar: "هَاتِفٌ", translit: "hātifun", fr: "téléphone", cat: "Cours 2" },
  { ar: "سَرِيرٌ", translit: "sarīrun", fr: "lit", cat: "Cours 2" },
  { ar: "مُنَبِّهٌ / رَنَّ", translit: "munabbihun / ranna", fr: "réveil / sonner", cat: "Cours 2" },
  { ar: "الْمِنْضَدَةُ", translit: "al-minḍadatu", fr: "la table de chevet", cat: "Cours 2" },
  { ar: "غَطَّى / أُغَطِّي بِالْفِرَاشِ", translit: "ghaṭṭā / ughaṭṭī bi-l-firāshi", fr: "couvrir / je couvre avec la couverture", cat: "Cours 2" },
  { ar: "بِجَانِبِ السِّتَارَةِ", translit: "bijānibi s-sitārati", fr: "à côté du rideau", cat: "Cours 2" },
  { ar: "سَجَّادَةٌ مُرَتَّبَةٌ ≠ فَوْضَوِيَّةٌ", translit: "sajjādatun murattabatun ≠ fawḍawiyyatun", fr: "un tapis rangé ≠ désordonné", cat: "Cours 2" },
  { ar: "يَمِينٌ ↔ يَسَارٌ", translit: "yamīnun ↔ yasārun", fr: "droite ↔ gauche", cat: "Cours 2" },
  { ar: "نَسِيتُ", translit: "nasītu", fr: "j'ai oublié", cat: "Cours 2" },
  { ar: "حَقِيبَةٌ", translit: "ḥaqībatun", fr: "sac à dos", cat: "Cours 2" },
  { ar: "الْمَغْسَلَةُ", translit: "al-maghsalatu", fr: "le lavabo", cat: "Cours 2" },
  { ar: "يَدَيْنِ", translit: "yadayni", fr: "les deux mains", cat: "Cours 2" },
  { ar: "يَغْسِلُ", translit: "yaghsilu", fr: "il lave", cat: "Cours 2" },
  { ar: "يَفْتَحُ الْحَنَفِيَّةَ", translit: "yaftaḥu l-ḥanafiyyata", fr: "il ouvre le robinet", cat: "Cours 2" }
];

// =====================================================================
// Paquets de départ par DIALECTE (vrai parler, pas l'arabe standard).
// Clés = id du preset (voir LANG_PRESETS dans app.js).
// Chaque mot = { ar, translit, fr, cat }. Termes vocalisés.
// =====================================================================
window.DIALECT_PACKS = {

  // 🇲🇦 Darija marocain
  darija: [
    { ar: "بْغِيت", translit: "bghit", fr: "je veux", cat: "Mots du quotidien" },
    { ar: "وَاخّا", translit: "wakha", fr: "d'accord / OK", cat: "Mots du quotidien" },
    { ar: "بِزّاف", translit: "bezzaf", fr: "beaucoup / trop", cat: "Mots du quotidien" },
    { ar: "شْوِيَّة", translit: "chwiya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "دَابَا", translit: "daba", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "مَزْيَان", translit: "mzyan", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "صَافِي", translit: "safi", fr: "ça suffit / voilà", cat: "Mots du quotidien" },
    { ar: "خُويَا", translit: "khoya", fr: "mon frère / mon pote", cat: "Mots du quotidien" },
    { ar: "دْيَالِي", translit: "dyali", fr: "à moi / le mien", cat: "Mots du quotidien" },
    { ar: "الحَانُوت", translit: "l-ḥanut", fr: "l'épicerie du coin", cat: "Mots du quotidien" },
    { ar: "أَتَاي", translit: "atay", fr: "le thé (à la menthe)", cat: "Mots du quotidien" },
    { ar: "كِي دَايِر؟", translit: "ki dayer?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "شْحَال؟", translit: "chḥal?", fr: "combien ?", cat: "Questions & politesse" },
    { ar: "فِين؟", translit: "fin?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيفَاش؟", translit: "kifach?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عْلاش؟", translit: "3lach?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عَافَاك", translit: "3afak", fr: "s'il te plaît", cat: "Questions & politesse" },
    { ar: "مَاكَايْن مُشْكِيل", translit: "makayn mushkil", fr: "il n'y a pas de problème", cat: "Questions & politesse" },
    { ar: "بَرَاكَا", translit: "baraka", fr: "ça suffit / arrête", cat: "Questions & politesse" },
    // Kit de survie
    { ar: "السَّلَامُ عْلِيكُم", translit: "ssalamu 3likom", fr: "bonjour (salut)", cat: "Kit de survie" },
    { ar: "بَارَاكَ الله فِيك", translit: "barak llah fik", fr: "merci", cat: "Kit de survie" },
    { ar: "إِيه", translit: "iyeh", fr: "oui", cat: "Kit de survie" },
    { ar: "لَا", translit: "la", fr: "non", cat: "Kit de survie" },
    { ar: "بِشْحَال؟", translit: "bechḥal?", fr: "combien ça coûte ?", cat: "Kit de survie" },
    { ar: "فِين كَايْن...؟", translit: "fin kayn...?", fr: "où se trouve... ?", cat: "Kit de survie" },
    { ar: "مَا فْهَمْتْش", translit: "ma fhemtch", fr: "je n'ai pas compris", cat: "Kit de survie" },
    { ar: "فِين كَايْن المِرْحَاض؟", translit: "fin kayn l-mirḥaḍ?", fr: "où sont les toilettes ?", cat: "Kit de survie" },
    { ar: "عَاوِنِّي عَافَاك", translit: "3awenni 3afak", fr: "aide-moi s'il te plaît", cat: "Kit de survie" },
    { ar: "الحْسَاب عَافَاك", translit: "l-ḥsab 3afak", fr: "l'addition s'il te plaît", cat: "Kit de survie" },
    { ar: "بِسْلَامَة", translit: "bslama", fr: "au revoir", cat: "Kit de survie" },
    // Se présenter
    { ar: "سْمِيتِي...", translit: "smiti...", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "عَنْدِي ... عَام", translit: "3andi ... 3am", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "أَنَا فْرَنْسَاوِي", translit: "ana fransawi", fr: "je suis français", cat: "Se présenter" },
    { ar: "كَنْسْكُن فْ...", translit: "kanskun f...", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "مِتْشَرّْفِين", translit: "mtcharrfin", fr: "enchanté", cat: "Se présenter" },
    { ar: "كَنْهْضَر شْوِيَّة دْيَال العَرَبِيَّة", translit: "kanhḍar chwiya dyal l-3arabiya", fr: "je parle un peu arabe", cat: "Se présenter" },
    { ar: "أَشْنُو سْمِيتَك؟", translit: "achno smitek?", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
    // Nombres
    { ar: "وَاحْد", translit: "waḥed", fr: "un (1)", cat: "Nombres" },
    { ar: "جُوج", translit: "jouj", fr: "deux (2)", cat: "Nombres" },
    { ar: "تْلَاتَة", translit: "tlata", fr: "trois (3)", cat: "Nombres" },
    { ar: "رْبْعَة", translit: "reb3a", fr: "quatre (4)", cat: "Nombres" },
    { ar: "خَمْسَة", translit: "khamsa", fr: "cinq (5)", cat: "Nombres" },
    { ar: "سْتَّة", translit: "setta", fr: "six (6)", cat: "Nombres" },
    { ar: "سْبْعَة", translit: "seb3a", fr: "sept (7)", cat: "Nombres" },
    { ar: "تْمَنْيَة", translit: "tmenya", fr: "huit (8)", cat: "Nombres" },
    { ar: "تْسْعُود", translit: "tes3oud", fr: "neuf (9)", cat: "Nombres" },
    { ar: "عَشْرَة", translit: "3achra", fr: "dix (10)", cat: "Nombres" },
    // Nourriture & boissons
    { ar: "المَا", translit: "l-ma", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "الخُبْز", translit: "l-khobz", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "القَهْوَة", translit: "l-qahwa", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "الحْلِيب", translit: "l-ḥlib", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "التُّفَّاح", translit: "t-tffaḥ", fr: "les pommes", cat: "Nourriture & boissons" },
    { ar: "اللْحَم", translit: "l-lḥem", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "الدْجَاج", translit: "d-djaj", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "الحُوت", translit: "l-ḥut", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "الخُضْرَة", translit: "l-khodra", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "السُّكَّر", translit: "s-sokkar", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "المَلْحَة", translit: "l-melḥa", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "الزِّيت", translit: "z-zit", fr: "l'huile", cat: "Nourriture & boissons" },
  ],

  // 🇪🇬 Égyptien
  egy: [
    { ar: "عَايِز", translit: "3ayez", fr: "je veux (homme)", cat: "Mots du quotidien" },
    { ar: "عَايْزَة", translit: "3ayza", fr: "je veux (femme)", cat: "Mots du quotidien" },
    { ar: "دِلْوَقْتِي", translit: "delwa2ti", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "كِدَه", translit: "keda", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "قَوِي", translit: "2awi", fr: "très / beaucoup", cat: "Mots du quotidien" },
    { ar: "شْوَيَّة", translit: "shwaya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "كْوَيِّس", translit: "kwayyes", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "حَاجَة", translit: "ḥaga", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "خَلَاص", translit: "khalaṣ", fr: "fini / ça suffit", cat: "Mots du quotidien" },
    { ar: "النَّهَارْدَه", translit: "el-naharda", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "بُكْرَة", translit: "bokra", fr: "demain", cat: "Mots du quotidien" },
    { ar: "إِمْبَارِح", translit: "embareḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "إِزَّيَّك؟", translit: "ezzayyak?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "فِين؟", translit: "fein?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "إِزَّاي؟", translit: "ezzay?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عَايِز إِيه؟", translit: "3ayez eh?", fr: "tu veux quoi ?", cat: "Questions & politesse" },
    { ar: "لِيه؟", translit: "leh?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عَشَان", translit: "3ashan", fr: "parce que / pour", cat: "Questions & politesse" },
    { ar: "مَعْلِشّ", translit: "ma3lesh", fr: "c'est pas grave / désolé", cat: "Questions & politesse" },
    // Kit de survie
    { ar: "السَّلَامُ عَلِيكُم", translit: "es-salamu 3aleykom", fr: "bonjour (salut)", cat: "Kit de survie" },
    { ar: "شُكْرًا", translit: "shukran", fr: "merci", cat: "Kit de survie" },
    { ar: "آيْوَة", translit: "aywa", fr: "oui", cat: "Kit de survie" },
    { ar: "لَأ", translit: "la2", fr: "non", cat: "Kit de survie" },
    { ar: "بِكَام؟", translit: "bikam?", fr: "combien ça coûte ?", cat: "Kit de survie" },
    { ar: "فِين...؟", translit: "fein...?", fr: "où est... ?", cat: "Kit de survie" },
    { ar: "مِش فَاهِم", translit: "mish fahem", fr: "je ne comprends pas", cat: "Kit de survie" },
    { ar: "فِين الحَمَّام؟", translit: "fein el-ḥammam?", fr: "où sont les toilettes ?", cat: "Kit de survie" },
    { ar: "مُمْكِن تْسَاعِدْنِي؟", translit: "momken tsa3edni?", fr: "peux-tu m'aider ?", cat: "Kit de survie" },
    { ar: "الحِسَاب لَو سَمَحْت", translit: "el-ḥesab law samaḥt", fr: "l'addition s'il vous plaît", cat: "Kit de survie" },
    { ar: "مَع السَّلَامَة", translit: "ma3 es-salama", fr: "au revoir", cat: "Kit de survie" },
    // Se présenter
    { ar: "اِسْمِي...", translit: "esmi...", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "عَنْدِي ... سَنَة", translit: "3andi ... sana", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "أَنَا فَرَنْسَاوِي", translit: "ana faransawi", fr: "je suis français", cat: "Se présenter" },
    { ar: "سَاكِن فِي...", translit: "saken fi...", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "فُرْصَة سَعِيدَة", translit: "forṣa sa3ida", fr: "enchanté", cat: "Se présenter" },
    { ar: "بَتْكَلِّم عَرَبِي شْوَيَّة", translit: "batkallem 3arabi shwaya", fr: "je parle un peu arabe", cat: "Se présenter" },
    { ar: "اِسْمَك إِيه؟", translit: "esmak eh?", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
    // Nombres
    { ar: "وَاحِد", translit: "waḥed", fr: "un (1)", cat: "Nombres" },
    { ar: "اِتْنِين", translit: "etnein", fr: "deux (2)", cat: "Nombres" },
    { ar: "تَلَاتَة", translit: "talata", fr: "trois (3)", cat: "Nombres" },
    { ar: "أَرْبَعَة", translit: "arba3a", fr: "quatre (4)", cat: "Nombres" },
    { ar: "خَمْسَة", translit: "khamsa", fr: "cinq (5)", cat: "Nombres" },
    { ar: "سِتَّة", translit: "setta", fr: "six (6)", cat: "Nombres" },
    { ar: "سَبْعَة", translit: "sab3a", fr: "sept (7)", cat: "Nombres" },
    { ar: "تَمَانْيَة", translit: "tamanya", fr: "huit (8)", cat: "Nombres" },
    { ar: "تِسْعَة", translit: "tes3a", fr: "neuf (9)", cat: "Nombres" },
    { ar: "عَشَرَة", translit: "3ashara", fr: "dix (10)", cat: "Nombres" },
    // Nourriture & boissons
    { ar: "مَيَّة", translit: "mayya", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "عِيش", translit: "3eish", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "قَهْوَة", translit: "2ahwa", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "شَاي", translit: "shay", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "لَبَن", translit: "laban", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "تُفَّاح", translit: "toffaḥ", fr: "les pommes", cat: "Nourriture & boissons" },
    { ar: "لَحْمَة", translit: "laḥma", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "فِرَاخ", translit: "firakh", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "سَمَك", translit: "samak", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "خُضَار", translit: "khoḍar", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "سُكَّر", translit: "sokkar", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "مَلْح", translit: "malḥ", fr: "le sel", cat: "Nourriture & boissons" },
  ],

  // 🇱🇧 Libanais
  leb: [
    { ar: "بَدِّي", translit: "baddi", fr: "je veux", cat: "Mots du quotidien" },
    { ar: "هَلَّق", translit: "halla2", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "هِيك", translit: "heik", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "كْتِير", translit: "ktir", fr: "beaucoup / très", cat: "Mots du quotidien" },
    { ar: "شْوَيّ", translit: "shwayy", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "مْنِيح", translit: "mnih", fr: "bien / bon", cat: "Mots du quotidien" },
    { ar: "شِي", translit: "shi", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "خَلَص", translit: "khalaṣ", fr: "fini / ça suffit", cat: "Mots du quotidien" },
    { ar: "يَعْنِي", translit: "ya3ni", fr: "c'est-à-dire / genre", cat: "Mots du quotidien" },
    { ar: "اليَوْم", translit: "lyom", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "بُكْرَا", translit: "bukra", fr: "demain", cat: "Mots du quotidien" },
    { ar: "مْبَارِح", translit: "mbeireḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "كِيفَك؟", translit: "kifak?", fr: "comment vas-tu ? (à un homme)", cat: "Questions & politesse" },
    { ar: "شُو؟", translit: "shu?", fr: "quoi ?", cat: "Questions & politesse" },
    { ar: "وِين؟", translit: "wein?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيف؟", translit: "kif?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "لِيش؟", translit: "leish?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "لَأَنُّو", translit: "la2anno", fr: "parce que", cat: "Questions & politesse" },
    { ar: "مَعْلِيش", translit: "ma3lish", fr: "c'est pas grave", cat: "Questions & politesse" },
    // Kit de survie
    { ar: "مَرْحَبَا", translit: "marḥaba", fr: "bonjour", cat: "Kit de survie" },
    { ar: "شُكْرًا", translit: "shukran", fr: "merci", cat: "Kit de survie" },
    { ar: "إِي", translit: "ei", fr: "oui", cat: "Kit de survie" },
    { ar: "لَأ", translit: "la2", fr: "non", cat: "Kit de survie" },
    { ar: "بْكَمّ؟", translit: "bkam?", fr: "combien ça coûte ?", cat: "Kit de survie" },
    { ar: "وِين...؟", translit: "wein...?", fr: "où est... ?", cat: "Kit de survie" },
    { ar: "مَا فْهِمِت", translit: "ma fhemet", fr: "je n'ai pas compris", cat: "Kit de survie" },
    { ar: "وِين الحَمَّام؟", translit: "wein el-ḥammam?", fr: "où sont les toilettes ?", cat: "Kit de survie" },
    { ar: "فِيك تْسَاعِدْنِي؟", translit: "fik tsa3edni?", fr: "peux-tu m'aider ?", cat: "Kit de survie" },
    { ar: "الحْسَاب مِن فَضْلَك", translit: "l-ḥseb min faḍlak", fr: "l'addition s'il vous plaît", cat: "Kit de survie" },
    { ar: "مَع السَّلَامَة", translit: "ma3 es-salame", fr: "au revoir", cat: "Kit de survie" },
    // Se présenter
    { ar: "اِسْمِي...", translit: "esme...", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "عُمْرِي ... سِنِة", translit: "3omre ... sene", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "أَنَا فَرَنْسَاوِي", translit: "ana faransawi", fr: "je suis français", cat: "Se présenter" },
    { ar: "سَاكِن بْـ...", translit: "saken b...", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "تْشَرَّفْنَا", translit: "tsharrafna", fr: "enchanté", cat: "Se présenter" },
    { ar: "بِحْكِي عَرَبِي شْوَيّ", translit: "beḥke 3arabe shwayy", fr: "je parle un peu arabe", cat: "Se présenter" },
    { ar: "شُو اِسْمَك؟", translit: "shu esmak?", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
    // Nombres
    { ar: "وَاحَد", translit: "waḥad", fr: "un (1)", cat: "Nombres" },
    { ar: "تْنِين", translit: "tnein", fr: "deux (2)", cat: "Nombres" },
    { ar: "تْلَاتِة", translit: "tleti", fr: "trois (3)", cat: "Nombres" },
    { ar: "أَرْبَعَة", translit: "arba3a", fr: "quatre (4)", cat: "Nombres" },
    { ar: "خَمْسِة", translit: "khamse", fr: "cinq (5)", cat: "Nombres" },
    { ar: "سِتِّة", translit: "sitte", fr: "six (6)", cat: "Nombres" },
    { ar: "سَبْعَة", translit: "sab3a", fr: "sept (7)", cat: "Nombres" },
    { ar: "تْمَانِة", translit: "tmene", fr: "huit (8)", cat: "Nombres" },
    { ar: "تِسْعَة", translit: "tes3a", fr: "neuf (9)", cat: "Nombres" },
    { ar: "عَشَرَة", translit: "3ashara", fr: "dix (10)", cat: "Nombres" },
    // Nourriture & boissons
    { ar: "مَيّ", translit: "mayy", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "خِبِز", translit: "khebez", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "قَهْوِة", translit: "2ahwe", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "شَاي", translit: "shay", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "حَلِيب", translit: "ḥalib", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "تُفَّاح", translit: "teffaḥ", fr: "les pommes", cat: "Nourriture & boissons" },
    { ar: "لَحْمِة", translit: "laḥme", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "دَجَاج", translit: "dajaj", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "سَمَك", translit: "samak", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "خُضْرَة", translit: "khedra", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "سُكَّر", translit: "sekkar", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "مِلِح", translit: "meleḥ", fr: "le sel", cat: "Nourriture & boissons" },
  ],

  // 🇹🇳 Tunisien
  tun: [
    { ar: "نْحِبّ", translit: "nḥeb", fr: "je veux / j'aime", cat: "Mots du quotidien" },
    { ar: "تَوَّا", translit: "tawwa", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "هَكَّا", translit: "hakka", fr: "comme ça / ainsi", cat: "Mots du quotidien" },
    { ar: "بَرْشَا", translit: "barcha", fr: "beaucoup / très", cat: "Mots du quotidien" },
    { ar: "شْوَيَّة", translit: "chwaya", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "بَاهِي", translit: "behi", fr: "bien / bon / OK", cat: "Mots du quotidien" },
    { ar: "حَاجَة", translit: "ḥaja", fr: "une chose / un truc", cat: "Mots du quotidien" },
    { ar: "بَرْكَة", translit: "barka", fr: "ça suffit / arrête", cat: "Mots du quotidien" },
    { ar: "فَمَّا", translit: "famma", fr: "il y a", cat: "Mots du quotidien" },
    { ar: "اليُوم", translit: "lyoum", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "غُدْوَة", translit: "ghodwa", fr: "demain", cat: "Mots du quotidien" },
    { ar: "البَارِح", translit: "el-bareḥ", fr: "hier", cat: "Mots du quotidien" },
    { ar: "شْنُوَّة؟", translit: "chnowa?", fr: "quoi ?", cat: "Questions & politesse" },
    { ar: "شْنِيَّة أَحْوَالِك؟", translit: "chnia aḥwalek?", fr: "comment vas-tu ?", cat: "Questions & politesse" },
    { ar: "وِين؟", translit: "win?", fr: "où ?", cat: "Questions & politesse" },
    { ar: "كِيفَاش؟", translit: "kifech?", fr: "comment ?", cat: "Questions & politesse" },
    { ar: "عْلَاش؟", translit: "3lech?", fr: "pourquoi ?", cat: "Questions & politesse" },
    { ar: "عْلَى خَاطِر", translit: "3la khater", fr: "parce que", cat: "Questions & politesse" },
    { ar: "يِزِّي", translit: "yezzi", fr: "arrête / ça suffit", cat: "Questions & politesse" },
    // Kit de survie
    { ar: "عَسْلَامَة", translit: "3aslema", fr: "bonjour", cat: "Kit de survie" },
    { ar: "يَعِيشِك", translit: "ya3ayshek", fr: "merci", cat: "Kit de survie" },
    { ar: "إِيه", translit: "ih", fr: "oui", cat: "Kit de survie" },
    { ar: "لَا", translit: "la", fr: "non", cat: "Kit de survie" },
    { ar: "بِقَدَّاش؟", translit: "b'qaddech?", fr: "combien ça coûte ?", cat: "Kit de survie" },
    { ar: "وِين...؟", translit: "win...?", fr: "où est... ?", cat: "Kit de survie" },
    { ar: "مَا فْهِمْتِش", translit: "ma fhemtich", fr: "je n'ai pas compris", cat: "Kit de survie" },
    { ar: "وِين التْوَالِيت؟", translit: "win et-twalit?", fr: "où sont les toilettes ?", cat: "Kit de survie" },
    { ar: "تْنَجِّم تْعَاوِنِّي؟", translit: "tnajjem t3awenni?", fr: "peux-tu m'aider ?", cat: "Kit de survie" },
    { ar: "الحْسَاب يَعِيشِك", translit: "l-ḥsab ya3ayshek", fr: "l'addition s'il te plaît", cat: "Kit de survie" },
    { ar: "بِالسْلَامَة", translit: "b'slema", fr: "au revoir", cat: "Kit de survie" },
    // Se présenter
    { ar: "إِسْمِي...", translit: "esmi...", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "عَنْدِي ... عَام", translit: "3andi ... 3am", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "أَنَا فْرَنْسِي", translit: "ana fransi", fr: "je suis français", cat: "Se présenter" },
    { ar: "نُسْكُن فِي...", translit: "noskon fi...", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "تْشَرَّفْنَا", translit: "tcharrafna", fr: "enchanté", cat: "Se présenter" },
    { ar: "نَحْكِي شْوَيَّة عَرْبِي", translit: "naḥki chwaya 3arbi", fr: "je parle un peu arabe", cat: "Se présenter" },
    { ar: "شْنُوَّة إِسْمِك؟", translit: "chnowa esmek?", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
    // Nombres
    { ar: "وَاحِد", translit: "waḥed", fr: "un (1)", cat: "Nombres" },
    { ar: "زُوز", translit: "zouz", fr: "deux (2)", cat: "Nombres" },
    { ar: "ثْلَاثَة", translit: "thletha", fr: "trois (3)", cat: "Nombres" },
    { ar: "أَرْبْعَة", translit: "arb3a", fr: "quatre (4)", cat: "Nombres" },
    { ar: "خَمْسَة", translit: "khamsa", fr: "cinq (5)", cat: "Nombres" },
    { ar: "سِتَّة", translit: "setta", fr: "six (6)", cat: "Nombres" },
    { ar: "سَبْعَة", translit: "sab3a", fr: "sept (7)", cat: "Nombres" },
    { ar: "ثْمَنْيَة", translit: "thmanya", fr: "huit (8)", cat: "Nombres" },
    { ar: "تِسْعَة", translit: "tes3a", fr: "neuf (9)", cat: "Nombres" },
    { ar: "عَشْرَة", translit: "3achra", fr: "dix (10)", cat: "Nombres" },
    // Nourriture & boissons
    { ar: "مَا", translit: "ma", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "خُبْز", translit: "khobz", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "قَهْوَة", translit: "qahwa", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "تَايْ", translit: "tey", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "حْلِيب", translit: "ḥlib", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "تُفَّاح", translit: "toffeḥ", fr: "les pommes", cat: "Nourriture & boissons" },
    { ar: "لْحَم", translit: "lḥam", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "دْجَاج", translit: "djej", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "حُوت", translit: "ḥut", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "خُضْرَة", translit: "khoḍra", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "سُكَّر", translit: "sokkor", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "مِلْح", translit: "melḥ", fr: "le sel", cat: "Nourriture & boissons" },
  ],

  // 🇬🇧 Anglais
  en: [
    { ar: "Hello", translit: "", fr: "bonjour / salut", cat: "Salutations & politesse" },
    { ar: "Good morning", translit: "", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Good evening", translit: "", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "Goodbye", translit: "", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Please", translit: "", fr: "s'il te plaît", cat: "Salutations & politesse" },
    { ar: "Thank you", translit: "", fr: "merci", cat: "Salutations & politesse" },
    { ar: "You're welcome", translit: "", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "Yes", translit: "", fr: "oui", cat: "Salutations & politesse" },
    { ar: "No", translit: "", fr: "non", cat: "Salutations & politesse" },
    { ar: "Sorry", translit: "", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Excuse me", translit: "", fr: "excuse-moi", cat: "Salutations & politesse" },
    { ar: "now", translit: "", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "today", translit: "", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "tomorrow", translit: "", fr: "demain", cat: "Mots du quotidien" },
    { ar: "yesterday", translit: "", fr: "hier", cat: "Mots du quotidien" },
    { ar: "here", translit: "", fr: "ici", cat: "Mots du quotidien" },
    { ar: "there", translit: "", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "good", translit: "", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "bad", translit: "", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "big", translit: "", fr: "grand", cat: "Mots du quotidien" },
    { ar: "small", translit: "", fr: "petit", cat: "Mots du quotidien" },
    { ar: "a lot", translit: "", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "a little", translit: "", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "zero", translit: "", fr: "zéro (0)", cat: "Nombres" },
    { ar: "one", translit: "", fr: "un (1)", cat: "Nombres" },
    { ar: "two", translit: "", fr: "deux (2)", cat: "Nombres" },
    { ar: "three", translit: "", fr: "trois (3)", cat: "Nombres" },
    { ar: "four", translit: "", fr: "quatre (4)", cat: "Nombres" },
    { ar: "five", translit: "", fr: "cinq (5)", cat: "Nombres" },
    { ar: "six", translit: "", fr: "six (6)", cat: "Nombres" },
    { ar: "seven", translit: "", fr: "sept (7)", cat: "Nombres" },
    { ar: "eight", translit: "", fr: "huit (8)", cat: "Nombres" },
    { ar: "nine", translit: "", fr: "neuf (9)", cat: "Nombres" },
    { ar: "ten", translit: "", fr: "dix (10)", cat: "Nombres" },
    { ar: "water", translit: "", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "bread", translit: "", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "coffee", translit: "", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "tea", translit: "", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "milk", translit: "", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "apple", translit: "", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "meat", translit: "", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "chicken", translit: "", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "fish", translit: "", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "vegetables", translit: "", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "sugar", translit: "", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "salt", translit: "", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "rice", translit: "", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "egg", translit: "", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "My name is...", translit: "", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "I am French", translit: "", fr: "je suis français", cat: "Se présenter" },
    { ar: "I live in...", translit: "", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Nice to meet you", translit: "", fr: "enchanté", cat: "Se présenter" },
    { ar: "I am ... years old", translit: "", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "I speak a little English", translit: "", fr: "je parle un peu anglais", cat: "Se présenter" },
    { ar: "What's your name?", translit: "", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇪🇸 Espagnol
  es: [
    { ar: "Hola", translit: "", fr: "bonjour / salut", cat: "Salutations & politesse" },
    { ar: "Buenos días", translit: "", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Buenas tardes", translit: "", fr: "bonjour / bonsoir", cat: "Salutations & politesse" },
    { ar: "Adiós", translit: "", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Por favor", translit: "", fr: "s'il te plaît", cat: "Salutations & politesse" },
    { ar: "Gracias", translit: "", fr: "merci", cat: "Salutations & politesse" },
    { ar: "De nada", translit: "", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "Sí", translit: "", fr: "oui", cat: "Salutations & politesse" },
    { ar: "No", translit: "", fr: "non", cat: "Salutations & politesse" },
    { ar: "Perdón", translit: "", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Disculpe", translit: "", fr: "excusez-moi", cat: "Salutations & politesse" },
    { ar: "ahora", translit: "", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "hoy", translit: "", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "mañana", translit: "", fr: "demain", cat: "Mots du quotidien" },
    { ar: "ayer", translit: "", fr: "hier", cat: "Mots du quotidien" },
    { ar: "aquí", translit: "", fr: "ici", cat: "Mots du quotidien" },
    { ar: "allí", translit: "", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "bueno", translit: "", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "malo", translit: "", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "grande", translit: "", fr: "grand", cat: "Mots du quotidien" },
    { ar: "pequeño", translit: "", fr: "petit", cat: "Mots du quotidien" },
    { ar: "mucho", translit: "", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "poco", translit: "", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "cero", translit: "", fr: "zéro (0)", cat: "Nombres" },
    { ar: "uno", translit: "", fr: "un (1)", cat: "Nombres" },
    { ar: "dos", translit: "", fr: "deux (2)", cat: "Nombres" },
    { ar: "tres", translit: "", fr: "trois (3)", cat: "Nombres" },
    { ar: "cuatro", translit: "", fr: "quatre (4)", cat: "Nombres" },
    { ar: "cinco", translit: "", fr: "cinq (5)", cat: "Nombres" },
    { ar: "seis", translit: "", fr: "six (6)", cat: "Nombres" },
    { ar: "siete", translit: "", fr: "sept (7)", cat: "Nombres" },
    { ar: "ocho", translit: "", fr: "huit (8)", cat: "Nombres" },
    { ar: "nueve", translit: "", fr: "neuf (9)", cat: "Nombres" },
    { ar: "diez", translit: "", fr: "dix (10)", cat: "Nombres" },
    { ar: "agua", translit: "", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "pan", translit: "", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "café", translit: "", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "té", translit: "", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "leche", translit: "", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "manzana", translit: "", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "carne", translit: "", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "pollo", translit: "", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "pescado", translit: "", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "verduras", translit: "", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "azúcar", translit: "", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "sal", translit: "", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "arroz", translit: "", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "huevo", translit: "", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Me llamo...", translit: "", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Soy francés", translit: "", fr: "je suis français", cat: "Se présenter" },
    { ar: "Vivo en...", translit: "", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Encantado", translit: "", fr: "enchanté", cat: "Se présenter" },
    { ar: "Tengo ... años", translit: "", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Hablo un poco de español", translit: "", fr: "je parle un peu espagnol", cat: "Se présenter" },
    { ar: "¿Cómo te llamas?", translit: "", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇩🇪 Allemand
  de: [
    { ar: "Hallo", translit: "", fr: "bonjour / salut", cat: "Salutations & politesse" },
    { ar: "Guten Morgen", translit: "", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Guten Abend", translit: "", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "Auf Wiedersehen", translit: "", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Bitte", translit: "", fr: "s'il te plaît", cat: "Salutations & politesse" },
    { ar: "Danke", translit: "", fr: "merci", cat: "Salutations & politesse" },
    { ar: "Gern geschehen", translit: "", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "Ja", translit: "", fr: "oui", cat: "Salutations & politesse" },
    { ar: "Nein", translit: "", fr: "non", cat: "Salutations & politesse" },
    { ar: "Entschuldigung", translit: "", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Entschuldigen Sie", translit: "", fr: "excusez-moi", cat: "Salutations & politesse" },
    { ar: "jetzt", translit: "", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "heute", translit: "", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "morgen", translit: "", fr: "demain", cat: "Mots du quotidien" },
    { ar: "gestern", translit: "", fr: "hier", cat: "Mots du quotidien" },
    { ar: "hier", translit: "", fr: "ici", cat: "Mots du quotidien" },
    { ar: "dort", translit: "", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "gut", translit: "", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "schlecht", translit: "", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "groß", translit: "", fr: "grand", cat: "Mots du quotidien" },
    { ar: "klein", translit: "", fr: "petit", cat: "Mots du quotidien" },
    { ar: "viel", translit: "", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "wenig", translit: "", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "null", translit: "", fr: "zéro (0)", cat: "Nombres" },
    { ar: "eins", translit: "", fr: "un (1)", cat: "Nombres" },
    { ar: "zwei", translit: "", fr: "deux (2)", cat: "Nombres" },
    { ar: "drei", translit: "", fr: "trois (3)", cat: "Nombres" },
    { ar: "vier", translit: "", fr: "quatre (4)", cat: "Nombres" },
    { ar: "fünf", translit: "", fr: "cinq (5)", cat: "Nombres" },
    { ar: "sechs", translit: "", fr: "six (6)", cat: "Nombres" },
    { ar: "sieben", translit: "", fr: "sept (7)", cat: "Nombres" },
    { ar: "acht", translit: "", fr: "huit (8)", cat: "Nombres" },
    { ar: "neun", translit: "", fr: "neuf (9)", cat: "Nombres" },
    { ar: "zehn", translit: "", fr: "dix (10)", cat: "Nombres" },
    { ar: "Wasser", translit: "", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "Brot", translit: "", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "Kaffee", translit: "", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "Tee", translit: "", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "Milch", translit: "", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "Apfel", translit: "", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "Fleisch", translit: "", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "Hähnchen", translit: "", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "Fisch", translit: "", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "Gemüse", translit: "", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "Zucker", translit: "", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "Salz", translit: "", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "Reis", translit: "", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "Ei", translit: "", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Ich heiße...", translit: "", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Ich bin Franzose", translit: "", fr: "je suis français", cat: "Se présenter" },
    { ar: "Ich wohne in...", translit: "", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Freut mich", translit: "", fr: "enchanté", cat: "Se présenter" },
    { ar: "Ich bin ... Jahre alt", translit: "", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Ich spreche ein bisschen Deutsch", translit: "", fr: "je parle un peu allemand", cat: "Se présenter" },
    { ar: "Wie heißt du?", translit: "", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇮🇹 Italien
  it: [
    { ar: "Ciao", translit: "", fr: "salut", cat: "Salutations & politesse" },
    { ar: "Buongiorno", translit: "", fr: "bonjour", cat: "Salutations & politesse" },
    { ar: "Buonasera", translit: "", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "Arrivederci", translit: "", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Per favore", translit: "", fr: "s'il te plaît", cat: "Salutations & politesse" },
    { ar: "Grazie", translit: "", fr: "merci", cat: "Salutations & politesse" },
    { ar: "Prego", translit: "", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "Sì", translit: "", fr: "oui", cat: "Salutations & politesse" },
    { ar: "No", translit: "", fr: "non", cat: "Salutations & politesse" },
    { ar: "Scusa", translit: "", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Mi scusi", translit: "", fr: "excusez-moi", cat: "Salutations & politesse" },
    { ar: "adesso", translit: "", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "oggi", translit: "", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "domani", translit: "", fr: "demain", cat: "Mots du quotidien" },
    { ar: "ieri", translit: "", fr: "hier", cat: "Mots du quotidien" },
    { ar: "qui", translit: "", fr: "ici", cat: "Mots du quotidien" },
    { ar: "lì", translit: "", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "buono", translit: "", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "cattivo", translit: "", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "grande", translit: "", fr: "grand", cat: "Mots du quotidien" },
    { ar: "piccolo", translit: "", fr: "petit", cat: "Mots du quotidien" },
    { ar: "molto", translit: "", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "poco", translit: "", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "zero", translit: "", fr: "zéro (0)", cat: "Nombres" },
    { ar: "uno", translit: "", fr: "un (1)", cat: "Nombres" },
    { ar: "due", translit: "", fr: "deux (2)", cat: "Nombres" },
    { ar: "tre", translit: "", fr: "trois (3)", cat: "Nombres" },
    { ar: "quattro", translit: "", fr: "quatre (4)", cat: "Nombres" },
    { ar: "cinque", translit: "", fr: "cinq (5)", cat: "Nombres" },
    { ar: "sei", translit: "", fr: "six (6)", cat: "Nombres" },
    { ar: "sette", translit: "", fr: "sept (7)", cat: "Nombres" },
    { ar: "otto", translit: "", fr: "huit (8)", cat: "Nombres" },
    { ar: "nove", translit: "", fr: "neuf (9)", cat: "Nombres" },
    { ar: "dieci", translit: "", fr: "dix (10)", cat: "Nombres" },
    { ar: "acqua", translit: "", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "pane", translit: "", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "caffè", translit: "", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "tè", translit: "", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "latte", translit: "", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "mela", translit: "", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "carne", translit: "", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "pollo", translit: "", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "pesce", translit: "", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "verdura", translit: "", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "zucchero", translit: "", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "sale", translit: "", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "riso", translit: "", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "uovo", translit: "", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Mi chiamo...", translit: "", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Sono francese", translit: "", fr: "je suis français", cat: "Se présenter" },
    { ar: "Abito a...", translit: "", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Piacere", translit: "", fr: "enchanté", cat: "Se présenter" },
    { ar: "Ho ... anni", translit: "", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Parlo un po' d'italiano", translit: "", fr: "je parle un peu italien", cat: "Se présenter" },
    { ar: "Come ti chiami?", translit: "", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇵🇹 Portugais
  pt: [
    { ar: "Olá", translit: "", fr: "bonjour / salut", cat: "Salutations & politesse" },
    { ar: "Bom dia", translit: "", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Boa noite", translit: "", fr: "bonsoir / bonne nuit", cat: "Salutations & politesse" },
    { ar: "Adeus", translit: "", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Por favor", translit: "", fr: "s'il te plaît", cat: "Salutations & politesse" },
    { ar: "Obrigado", translit: "", fr: "merci", cat: "Salutations & politesse" },
    { ar: "De nada", translit: "", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "Sim", translit: "", fr: "oui", cat: "Salutations & politesse" },
    { ar: "Não", translit: "", fr: "non", cat: "Salutations & politesse" },
    { ar: "Desculpa", translit: "", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Com licença", translit: "", fr: "excusez-moi", cat: "Salutations & politesse" },
    { ar: "agora", translit: "", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "hoje", translit: "", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "amanhã", translit: "", fr: "demain", cat: "Mots du quotidien" },
    { ar: "ontem", translit: "", fr: "hier", cat: "Mots du quotidien" },
    { ar: "aqui", translit: "", fr: "ici", cat: "Mots du quotidien" },
    { ar: "ali", translit: "", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "bom", translit: "", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "mau", translit: "", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "grande", translit: "", fr: "grand", cat: "Mots du quotidien" },
    { ar: "pequeno", translit: "", fr: "petit", cat: "Mots du quotidien" },
    { ar: "muito", translit: "", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "pouco", translit: "", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "zero", translit: "", fr: "zéro (0)", cat: "Nombres" },
    { ar: "um", translit: "", fr: "un (1)", cat: "Nombres" },
    { ar: "dois", translit: "", fr: "deux (2)", cat: "Nombres" },
    { ar: "três", translit: "", fr: "trois (3)", cat: "Nombres" },
    { ar: "quatro", translit: "", fr: "quatre (4)", cat: "Nombres" },
    { ar: "cinco", translit: "", fr: "cinq (5)", cat: "Nombres" },
    { ar: "seis", translit: "", fr: "six (6)", cat: "Nombres" },
    { ar: "sete", translit: "", fr: "sept (7)", cat: "Nombres" },
    { ar: "oito", translit: "", fr: "huit (8)", cat: "Nombres" },
    { ar: "nove", translit: "", fr: "neuf (9)", cat: "Nombres" },
    { ar: "dez", translit: "", fr: "dix (10)", cat: "Nombres" },
    { ar: "água", translit: "", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "pão", translit: "", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "café", translit: "", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "chá", translit: "", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "leite", translit: "", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "maçã", translit: "", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "carne", translit: "", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "frango", translit: "", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "peixe", translit: "", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "legumes", translit: "", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "açúcar", translit: "", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "sal", translit: "", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "arroz", translit: "", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "ovo", translit: "", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Chamo-me...", translit: "", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Sou francês", translit: "", fr: "je suis français", cat: "Se présenter" },
    { ar: "Moro em...", translit: "", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Prazer", translit: "", fr: "enchanté", cat: "Se présenter" },
    { ar: "Tenho ... anos", translit: "", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Falo um pouco de português", translit: "", fr: "je parle un peu portugais", cat: "Se présenter" },
    { ar: "Como te chamas?", translit: "", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇷🇺 Russe
  ru: [
    { ar: "Привет", translit: "privet", fr: "salut", cat: "Salutations & politesse" },
    { ar: "Здравствуйте", translit: "zdravstvuyte", fr: "bonjour (formel)", cat: "Salutations & politesse" },
    { ar: "Доброе утро", translit: "dobroye utro", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Добрый вечер", translit: "dobryy vecher", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "До свидания", translit: "do svidaniya", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Пожалуйста", translit: "pozhaluysta", fr: "s'il te plaît / de rien", cat: "Salutations & politesse" },
    { ar: "Спасибо", translit: "spasibo", fr: "merci", cat: "Salutations & politesse" },
    { ar: "Да", translit: "da", fr: "oui", cat: "Salutations & politesse" },
    { ar: "Нет", translit: "net", fr: "non", cat: "Salutations & politesse" },
    { ar: "Извините", translit: "izvinite", fr: "excusez-moi / pardon", cat: "Salutations & politesse" },
    { ar: "сейчас", translit: "seychas", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "сегодня", translit: "segodnya", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "завтра", translit: "zavtra", fr: "demain", cat: "Mots du quotidien" },
    { ar: "вчера", translit: "vchera", fr: "hier", cat: "Mots du quotidien" },
    { ar: "здесь", translit: "zdes", fr: "ici", cat: "Mots du quotidien" },
    { ar: "там", translit: "tam", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "хорошо", translit: "khorosho", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "плохо", translit: "plokho", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "большой", translit: "bolshoy", fr: "grand", cat: "Mots du quotidien" },
    { ar: "маленький", translit: "malenkiy", fr: "petit", cat: "Mots du quotidien" },
    { ar: "много", translit: "mnogo", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "мало", translit: "malo", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "ноль", translit: "nol", fr: "zéro (0)", cat: "Nombres" },
    { ar: "один", translit: "odin", fr: "un (1)", cat: "Nombres" },
    { ar: "два", translit: "dva", fr: "deux (2)", cat: "Nombres" },
    { ar: "три", translit: "tri", fr: "trois (3)", cat: "Nombres" },
    { ar: "четыре", translit: "chetyre", fr: "quatre (4)", cat: "Nombres" },
    { ar: "пять", translit: "pyat", fr: "cinq (5)", cat: "Nombres" },
    { ar: "шесть", translit: "shest", fr: "six (6)", cat: "Nombres" },
    { ar: "семь", translit: "sem", fr: "sept (7)", cat: "Nombres" },
    { ar: "восемь", translit: "vosem", fr: "huit (8)", cat: "Nombres" },
    { ar: "девять", translit: "devyat", fr: "neuf (9)", cat: "Nombres" },
    { ar: "десять", translit: "desyat", fr: "dix (10)", cat: "Nombres" },
    { ar: "вода", translit: "voda", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "хлеб", translit: "khleb", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "кофе", translit: "kofe", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "чай", translit: "chay", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "молоко", translit: "moloko", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "яблоко", translit: "yabloko", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "мясо", translit: "myaso", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "курица", translit: "kuritsa", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "рыба", translit: "ryba", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "овощи", translit: "ovoshchi", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "сахар", translit: "sakhar", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "соль", translit: "sol", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "рис", translit: "ris", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "яйцо", translit: "yaytso", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Меня зовут...", translit: "menya zovut", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Я француз", translit: "ya frantsuz", fr: "je suis français", cat: "Se présenter" },
    { ar: "Я живу в...", translit: "ya zhivu v", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Очень приятно", translit: "ochen priyatno", fr: "enchanté", cat: "Se présenter" },
    { ar: "Мне ... лет", translit: "mne ... let", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Я немного говорю по-русски", translit: "ya nemnogo govoryu po-russki", fr: "je parle un peu russe", cat: "Se présenter" },
    { ar: "Как тебя зовут?", translit: "kak tebya zovut", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇯🇵 Japonais
  ja: [
    { ar: "こんにちは", translit: "konnichiwa", fr: "bonjour", cat: "Salutations & politesse" },
    { ar: "おはよう", translit: "ohayō", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "こんばんは", translit: "konbanwa", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "さようなら", translit: "sayōnara", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "お願いします", translit: "onegaishimasu", fr: "s'il vous plaît", cat: "Salutations & politesse" },
    { ar: "ありがとう", translit: "arigatō", fr: "merci", cat: "Salutations & politesse" },
    { ar: "どういたしまして", translit: "dōitashimashite", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "はい", translit: "hai", fr: "oui", cat: "Salutations & politesse" },
    { ar: "いいえ", translit: "iie", fr: "non", cat: "Salutations & politesse" },
    { ar: "すみません", translit: "sumimasen", fr: "excusez-moi / pardon", cat: "Salutations & politesse" },
    { ar: "今", translit: "ima", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "今日", translit: "kyō", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "明日", translit: "ashita", fr: "demain", cat: "Mots du quotidien" },
    { ar: "昨日", translit: "kinō", fr: "hier", cat: "Mots du quotidien" },
    { ar: "ここ", translit: "koko", fr: "ici", cat: "Mots du quotidien" },
    { ar: "そこ", translit: "soko", fr: "là", cat: "Mots du quotidien" },
    { ar: "いい", translit: "ii", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "悪い", translit: "warui", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "大きい", translit: "ōkii", fr: "grand", cat: "Mots du quotidien" },
    { ar: "小さい", translit: "chiisai", fr: "petit", cat: "Mots du quotidien" },
    { ar: "たくさん", translit: "takusan", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "少し", translit: "sukoshi", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "ゼロ", translit: "zero", fr: "zéro (0)", cat: "Nombres" },
    { ar: "一", translit: "ichi", fr: "un (1)", cat: "Nombres" },
    { ar: "二", translit: "ni", fr: "deux (2)", cat: "Nombres" },
    { ar: "三", translit: "san", fr: "trois (3)", cat: "Nombres" },
    { ar: "四", translit: "yon", fr: "quatre (4)", cat: "Nombres" },
    { ar: "五", translit: "go", fr: "cinq (5)", cat: "Nombres" },
    { ar: "六", translit: "roku", fr: "six (6)", cat: "Nombres" },
    { ar: "七", translit: "nana", fr: "sept (7)", cat: "Nombres" },
    { ar: "八", translit: "hachi", fr: "huit (8)", cat: "Nombres" },
    { ar: "九", translit: "kyū", fr: "neuf (9)", cat: "Nombres" },
    { ar: "十", translit: "jū", fr: "dix (10)", cat: "Nombres" },
    { ar: "水", translit: "mizu", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "パン", translit: "pan", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "コーヒー", translit: "kōhī", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "お茶", translit: "ocha", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "牛乳", translit: "gyūnyū", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "りんご", translit: "ringo", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "肉", translit: "niku", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "鶏肉", translit: "toriniku", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "魚", translit: "sakana", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "野菜", translit: "yasai", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "砂糖", translit: "satō", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "塩", translit: "shio", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "ご飯", translit: "gohan", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "卵", translit: "tamago", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "私の名前は...", translit: "watashi no namae wa", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "私はフランス人です", translit: "watashi wa furansujin desu", fr: "je suis français", cat: "Se présenter" },
    { ar: "...に住んでいます", translit: "...ni sundeimasu", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "はじめまして", translit: "hajimemashite", fr: "enchanté", cat: "Se présenter" },
    { ar: "...歳です", translit: "...sai desu", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "日本語を少し話します", translit: "nihongo o sukoshi hanashimasu", fr: "je parle un peu japonais", cat: "Se présenter" },
    { ar: "お名前は何ですか", translit: "onamae wa nan desu ka", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇨🇳 Chinois
  zh: [
    { ar: "你好", translit: "nǐ hǎo", fr: "bonjour", cat: "Salutations & politesse" },
    { ar: "早上好", translit: "zǎoshang hǎo", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "晚上好", translit: "wǎnshàng hǎo", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "再见", translit: "zàijiàn", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "请", translit: "qǐng", fr: "s'il vous plaît", cat: "Salutations & politesse" },
    { ar: "谢谢", translit: "xièxie", fr: "merci", cat: "Salutations & politesse" },
    { ar: "不客气", translit: "bù kèqi", fr: "de rien", cat: "Salutations & politesse" },
    { ar: "是", translit: "shì", fr: "oui", cat: "Salutations & politesse" },
    { ar: "不", translit: "bù", fr: "non", cat: "Salutations & politesse" },
    { ar: "对不起", translit: "duìbuqǐ", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "现在", translit: "xiànzài", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "今天", translit: "jīntiān", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "明天", translit: "míngtiān", fr: "demain", cat: "Mots du quotidien" },
    { ar: "昨天", translit: "zuótiān", fr: "hier", cat: "Mots du quotidien" },
    { ar: "这里", translit: "zhèlǐ", fr: "ici", cat: "Mots du quotidien" },
    { ar: "那里", translit: "nàlǐ", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "好", translit: "hǎo", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "坏", translit: "huài", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "大", translit: "dà", fr: "grand", cat: "Mots du quotidien" },
    { ar: "小", translit: "xiǎo", fr: "petit", cat: "Mots du quotidien" },
    { ar: "很多", translit: "hěn duō", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "一点", translit: "yìdiǎn", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "零", translit: "líng", fr: "zéro (0)", cat: "Nombres" },
    { ar: "一", translit: "yī", fr: "un (1)", cat: "Nombres" },
    { ar: "二", translit: "èr", fr: "deux (2)", cat: "Nombres" },
    { ar: "三", translit: "sān", fr: "trois (3)", cat: "Nombres" },
    { ar: "四", translit: "sì", fr: "quatre (4)", cat: "Nombres" },
    { ar: "五", translit: "wǔ", fr: "cinq (5)", cat: "Nombres" },
    { ar: "六", translit: "liù", fr: "six (6)", cat: "Nombres" },
    { ar: "七", translit: "qī", fr: "sept (7)", cat: "Nombres" },
    { ar: "八", translit: "bā", fr: "huit (8)", cat: "Nombres" },
    { ar: "九", translit: "jiǔ", fr: "neuf (9)", cat: "Nombres" },
    { ar: "十", translit: "shí", fr: "dix (10)", cat: "Nombres" },
    { ar: "水", translit: "shuǐ", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "面包", translit: "miànbāo", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "咖啡", translit: "kāfēi", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "茶", translit: "chá", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "牛奶", translit: "niúnǎi", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "苹果", translit: "píngguǒ", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "肉", translit: "ròu", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "鸡肉", translit: "jīròu", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "鱼", translit: "yú", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "蔬菜", translit: "shūcài", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "糖", translit: "táng", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "盐", translit: "yán", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "米饭", translit: "mǐfàn", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "鸡蛋", translit: "jīdàn", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "我叫...", translit: "wǒ jiào", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "我是法国人", translit: "wǒ shì fǎguórén", fr: "je suis français", cat: "Se présenter" },
    { ar: "我住在...", translit: "wǒ zhù zài", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "很高兴认识你", translit: "hěn gāoxìng rènshi nǐ", fr: "enchanté", cat: "Se présenter" },
    { ar: "我...岁", translit: "wǒ ... suì", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "我会说一点中文", translit: "wǒ huì shuō yìdiǎn zhōngwén", fr: "je parle un peu chinois", cat: "Se présenter" },
    { ar: "你叫什么名字", translit: "nǐ jiào shénme míngzi", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

  // 🇬🇷 Grec
  el: [
    { ar: "Γεια σου", translit: "ya sou", fr: "bonjour / salut", cat: "Salutations & politesse" },
    { ar: "Καλημέρα", translit: "kaliméra", fr: "bonjour (le matin)", cat: "Salutations & politesse" },
    { ar: "Καλησπέρα", translit: "kalispéra", fr: "bonsoir", cat: "Salutations & politesse" },
    { ar: "Αντίο", translit: "antío", fr: "au revoir", cat: "Salutations & politesse" },
    { ar: "Παρακαλώ", translit: "parakaló", fr: "s'il te plaît / de rien", cat: "Salutations & politesse" },
    { ar: "Ευχαριστώ", translit: "efcharistó", fr: "merci", cat: "Salutations & politesse" },
    { ar: "Ναι", translit: "ne", fr: "oui", cat: "Salutations & politesse" },
    { ar: "Όχι", translit: "óchi", fr: "non", cat: "Salutations & politesse" },
    { ar: "Συγγνώμη", translit: "signómi", fr: "désolé / pardon", cat: "Salutations & politesse" },
    { ar: "Καληνύχτα", translit: "kaliníchta", fr: "bonne nuit", cat: "Salutations & politesse" },
    { ar: "τώρα", translit: "tóra", fr: "maintenant", cat: "Mots du quotidien" },
    { ar: "σήμερα", translit: "símera", fr: "aujourd'hui", cat: "Mots du quotidien" },
    { ar: "αύριο", translit: "ávrio", fr: "demain", cat: "Mots du quotidien" },
    { ar: "χθες", translit: "chthes", fr: "hier", cat: "Mots du quotidien" },
    { ar: "εδώ", translit: "edó", fr: "ici", cat: "Mots du quotidien" },
    { ar: "εκεί", translit: "ekí", fr: "là-bas", cat: "Mots du quotidien" },
    { ar: "καλό", translit: "kaló", fr: "bon / bien", cat: "Mots du quotidien" },
    { ar: "κακό", translit: "kakó", fr: "mauvais", cat: "Mots du quotidien" },
    { ar: "μεγάλο", translit: "megálo", fr: "grand", cat: "Mots du quotidien" },
    { ar: "μικρό", translit: "mikró", fr: "petit", cat: "Mots du quotidien" },
    { ar: "πολύ", translit: "polí", fr: "beaucoup", cat: "Mots du quotidien" },
    { ar: "λίγο", translit: "lígo", fr: "un peu", cat: "Mots du quotidien" },
    { ar: "μηδέν", translit: "midén", fr: "zéro (0)", cat: "Nombres" },
    { ar: "ένα", translit: "éna", fr: "un (1)", cat: "Nombres" },
    { ar: "δύο", translit: "dío", fr: "deux (2)", cat: "Nombres" },
    { ar: "τρία", translit: "tría", fr: "trois (3)", cat: "Nombres" },
    { ar: "τέσσερα", translit: "téssera", fr: "quatre (4)", cat: "Nombres" },
    { ar: "πέντε", translit: "pénde", fr: "cinq (5)", cat: "Nombres" },
    { ar: "έξι", translit: "éxi", fr: "six (6)", cat: "Nombres" },
    { ar: "εφτά", translit: "eftá", fr: "sept (7)", cat: "Nombres" },
    { ar: "οκτώ", translit: "októ", fr: "huit (8)", cat: "Nombres" },
    { ar: "εννέα", translit: "ennéa", fr: "neuf (9)", cat: "Nombres" },
    { ar: "δέκα", translit: "déka", fr: "dix (10)", cat: "Nombres" },
    { ar: "νερό", translit: "neró", fr: "l'eau", cat: "Nourriture & boissons" },
    { ar: "ψωμί", translit: "psomí", fr: "le pain", cat: "Nourriture & boissons" },
    { ar: "καφές", translit: "kafés", fr: "le café", cat: "Nourriture & boissons" },
    { ar: "τσάι", translit: "tsái", fr: "le thé", cat: "Nourriture & boissons" },
    { ar: "γάλα", translit: "gála", fr: "le lait", cat: "Nourriture & boissons" },
    { ar: "μήλο", translit: "mílo", fr: "la pomme", cat: "Nourriture & boissons" },
    { ar: "κρέας", translit: "kréas", fr: "la viande", cat: "Nourriture & boissons" },
    { ar: "κοτόπουλο", translit: "kotópoulo", fr: "le poulet", cat: "Nourriture & boissons" },
    { ar: "ψάρι", translit: "psári", fr: "le poisson", cat: "Nourriture & boissons" },
    { ar: "λαχανικά", translit: "lachaniká", fr: "les légumes", cat: "Nourriture & boissons" },
    { ar: "ζάχαρη", translit: "záchari", fr: "le sucre", cat: "Nourriture & boissons" },
    { ar: "αλάτι", translit: "aláti", fr: "le sel", cat: "Nourriture & boissons" },
    { ar: "ρύζι", translit: "rízi", fr: "le riz", cat: "Nourriture & boissons" },
    { ar: "αυγό", translit: "avgó", fr: "l'œuf", cat: "Nourriture & boissons" },
    { ar: "Με λένε...", translit: "me léne", fr: "je m'appelle...", cat: "Se présenter" },
    { ar: "Είμαι Γάλλος", translit: "íme Gállos", fr: "je suis français", cat: "Se présenter" },
    { ar: "Μένω στο...", translit: "méno sto", fr: "j'habite à...", cat: "Se présenter" },
    { ar: "Χάρηκα", translit: "chárika", fr: "enchanté", cat: "Se présenter" },
    { ar: "Είμαι ... χρονών", translit: "íme ... chronón", fr: "j'ai ... ans", cat: "Se présenter" },
    { ar: "Μιλάω λίγα ελληνικά", translit: "miláo líga elliniká", fr: "je parle un peu grec", cat: "Se présenter" },
    { ar: "Πώς σε λένε;", translit: "pos se léne", fr: "comment t'appelles-tu ?", cat: "Se présenter" },
  ],

};
