// Paquet de départ — vocabulaire arabe (toujours vocalisé, avec les voyelles).
// Chaque mot = { ar, translit, fr, cat }  (cat = catégorie / thème).
// Tu peux éditer cette liste à la main, ou ajouter des mots directement dans le site.
// Bouton « Réinitialiser » = repartir de cette liste.

window.DEFAULT_WORDS = [
  // 🛏️ La chambre et la maison
  { ar: "فِي غُرْفَتِي", translit: "fī ghurfatī", fr: "dans ma chambre", cat: "Chambre & maison" },
  { ar: "سَرِيرٌ", translit: "sarīrun", fr: "un lit", cat: "Chambre & maison" },
  { ar: "بِطَّانِيَّةٌ", translit: "biṭṭāniyyatun", fr: "une couverture", cat: "Chambre & maison" },
  { ar: "خِزَانَةٌ", translit: "khizānatun", fr: "une armoire / un placard", cat: "Chambre & maison" },
  { ar: "أَنَامُ عَلَى السَّرِيرِ", translit: "anāmu ʿalā s-sarīri", fr: "je dors sur le lit", cat: "Chambre & maison" },
  { ar: "أَضَعُ", translit: "aḍaʿu", fr: "je mets / je pose", cat: "Chambre & maison" },
  { ar: "أُغَطِّي", translit: "ughaṭṭī", fr: "je couvre", cat: "Chambre & maison" },
  { ar: "الوِسَادَةُ", translit: "al-wisādatu", fr: "l'oreiller", cat: "Chambre & maison" },
  { ar: "المَكْتَبُ", translit: "al-maktabu", fr: "le bureau de travail", cat: "Chambre & maison" },
  { ar: "أَقْلَامٌ", translit: "aqlāmun", fr: "des stylos", cat: "Chambre & maison" },
  { ar: "حَاسُوبٌ", translit: "ḥāsūbun", fr: "ordinateur", cat: "Chambre & maison" },
  { ar: "المِصْبَاحُ", translit: "al-miṣbāḥu", fr: "la lampe", cat: "Chambre & maison" },
  { ar: "نَافِذَةٌ", translit: "nāfidhatun", fr: "fenêtre", cat: "Chambre & maison" },
  { ar: "نَوَافِذُ", translit: "nawāfidhu", fr: "fenêtres (pluriel)", cat: "Chambre & maison" },
  { ar: "سِتَارَةٌ", translit: "sitāratun", fr: "rideau", cat: "Chambre & maison" },
  { ar: "سَتَائِرُ", translit: "satāʾiru", fr: "rideaux", cat: "Chambre & maison" },
  { ar: "سَجَّادَةٌ", translit: "sajjādatun", fr: "tapis", cat: "Chambre & maison" },
  { ar: "جُرَابٌ", translit: "jurābun", fr: "chaussette", cat: "Chambre & maison" },
  { ar: "جَوَارِبُ", translit: "jawāribu", fr: "chaussettes", cat: "Chambre & maison" },

  // 🧼 La salle de bain et l'hygiène
  { ar: "فِي الحَمَّامِ", translit: "fī l-ḥammāmi", fr: "dans la salle de bain", cat: "Salle de bain" },
  { ar: "حَوْضٌ", translit: "ḥawḍun", fr: "un lavabo / une baignoire", cat: "Salle de bain" },
  { ar: "المُغْتَسَلُ", translit: "al-mughtasalu", fr: "le lavabo", cat: "Salle de bain" },
  { ar: "صَابُونٌ", translit: "ṣābūnun", fr: "savon", cat: "Salle de bain" },
  { ar: "مِرْآةٌ", translit: "mirʾātun", fr: "miroir", cat: "Salle de bain" },
  { ar: "مِنْشَفَةٌ", translit: "minshafatun", fr: "serviette / essuie-tout", cat: "Salle de bain" },
  { ar: "جَسَدٌ", translit: "jasadun", fr: "corps", cat: "Salle de bain" },
  { ar: "جِسْمٌ", translit: "jismun", fr: "corps", cat: "Salle de bain" },
  { ar: "أُنَظِّفُ", translit: "unaẓẓifu", fr: "je nettoie", cat: "Salle de bain" },
  { ar: "سَلَّةُ الغَسِيلِ", translit: "sallatu l-ghasīli", fr: "panier à linge", cat: "Salle de bain" },
  { ar: "أَجْلِسُ", translit: "ajlisu", fr: "je m'assois", cat: "Salle de bain" },
  { ar: "أَبُولُ", translit: "abūlu", fr: "je fais pipi", cat: "Salle de bain" },
  { ar: "أَقْضِي حَاجَتِي", translit: "aqḍī ḥājatī", fr: "faire ses besoins", cat: "Salle de bain" },
  { ar: "البُرَازُ", translit: "al-burāzu", fr: "les selles / matières fécales", cat: "Salle de bain" },

  // 🍳 La cuisine, les ustensiles et les verbes
  { ar: "المَطْبَخُ", translit: "al-maṭbakhu", fr: "la cuisine", cat: "Cuisine" },
  { ar: "الأَوَانِي", translit: "al-awānī", fr: "la vaisselle", cat: "Cuisine" },
  { ar: "نُجَفِّفُ", translit: "nujaffifu", fr: "nous séchons", cat: "Cuisine" },
  { ar: "تَسْتَعْجِلُ", translit: "tastaʿjilu", fr: "tu te dépêches / tu es pressé", cat: "Cuisine" },
  { ar: "أَسْتَعْمِلُ", translit: "astaʿmilu", fr: "j'utilise", cat: "Cuisine" },
  { ar: "الفُرْنُ", translit: "al-furnu", fr: "le four", cat: "Cuisine" },
  { ar: "المَوْقِدُ", translit: "al-mawqidu", fr: "la plaque de cuisson / le réchaud", cat: "Cuisine" },
  { ar: "شَفَّاطٌ", translit: "shaffāṭun", fr: "hotte aspirante", cat: "Cuisine" },
  { ar: "المِصْفَاةُ", translit: "al-miṣfātu", fr: "la passoire", cat: "Cuisine" },
  { ar: "أُصَفِّي الطَّعَامَ فِي المَاءِ", translit: "uṣaffī ṭ-ṭaʿāma fī l-māʾi", fr: "j'égoutte la nourriture (dans l'eau)", cat: "Cuisine" },
  { ar: "خَلَّاطٌ", translit: "khallāṭun", fr: "mixeur", cat: "Cuisine" },
  { ar: "إِبْرِيقُ الشَّايِ", translit: "ibrīqu sh-shāyi", fr: "la théière", cat: "Cuisine" },
  { ar: "الشَّوْكَةُ", translit: "ash-shawkatu", fr: "la fourchette", cat: "Cuisine" },
  { ar: "المِقْلَاةُ", translit: "al-miqlātu", fr: "la poêle", cat: "Cuisine" },
  { ar: "القِدْرُ", translit: "al-qidru", fr: "la marmite / la casserole", cat: "Cuisine" },
  { ar: "لَوْحَةُ التَّقْطِيعِ", translit: "lawḥatu t-taqṭīʿi", fr: "planche à découper", cat: "Cuisine" },
  { ar: "أَطْبُخُ الطَّعَامَ", translit: "aṭbukhu ṭ-ṭaʿāma", fr: "je cuisine / je prépare le repas", cat: "Cuisine" },
  { ar: "أَكْوَابٌ", translit: "akwābun", fr: "des verres", cat: "Cuisine" },
  { ar: "صَحْنٌ", translit: "ṣaḥnun", fr: "assiette", cat: "Cuisine" },
  { ar: "صُحُونٌ", translit: "ṣuḥūnun", fr: "assiettes", cat: "Cuisine" },
  { ar: "المِلْعَقَةُ", translit: "al-milʿaqatu", fr: "la cuillère", cat: "Cuisine" },
  { ar: "الغَلَّايَةُ", translit: "al-ghallāyatu", fr: "la bouilloire", cat: "Cuisine" },
  { ar: "السِّكِّينُ", translit: "as-sikkīnu", fr: "le couteau", cat: "Cuisine" },
  { ar: "مِكْوَاةٌ", translit: "mikwātun", fr: "un fer à repasser", cat: "Cuisine" },
  { ar: "أَكْوِي", translit: "akwī", fr: "je repasse", cat: "Cuisine" },
  { ar: "إِبْرِيقٌ", translit: "ibrīqun", fr: "carafe / broc", cat: "Cuisine" },
  { ar: "أُفْرِغُ", translit: "ufrighu", fr: "je verse / je vide", cat: "Cuisine" },
  { ar: "أَفْرَغَ", translit: "afragha", fr: "renverser / vider (la nourriture)", cat: "Cuisine" },
  { ar: "الحِسَاءُ", translit: "al-ḥisāʾu", fr: "la soupe", cat: "Cuisine" },
  { ar: "بَيْضٌ", translit: "bayḍun", fr: "des œufs", cat: "Cuisine" }
];
